sudo: required
services: docker
language: generic

before_install:
  - docker build -t dockerquark/docker_practice -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerquark/docker_practice yarn test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker_practice"
  env: "DockerPractice-env"
  bucket_name: "elasticbeanstalk-eu-west-2-261235767811"
  bucket_path: "docker_practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY